name: ML Pipeline CI

on:
  # push:
  #   branches: [ main, master  ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        python -m pip install --upgrade pip
        pip install pytest great_expectations pandas scikit-learn flake8 black mypy pytest-cov xgboost mlflow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 day5/演習3 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 day5/演習3 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        
    - name: Format check with black
      run: |
        black --check day5/演習3
        
    - name: Run data tests
      run: |
        pytest day5/演習3/tests/test_data.py -v
        
    - name: Run model tests
      run: |
        pytest day5/演習3/tests/test_model.py -v

    - name: Archive mlruns if exists
      if: always()
      run: |
        if [ -d "mlruns" ] && [ "$(ls -A mlruns)" ]; then
          echo "Found mlruns. Creating archive..."
          tar -czf mlflow-runs.tar.gz mlruns
        else
          echo "No mlruns directory found or it is empty. Skipping archive."
        fi

    - name: Upload MLflow runs artifact
      if: always() && hashFiles('mlflow-runs.tar.gz') != ''
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-runs
        path: mlflow-runs.tar.gz